from typing import List
from models import Persona, ChatRoom, AvatarType, ChatMessage

# CONST
personas: List[Persona] = [
    Persona(
        id="1",
        name="Sophia",
        role="law",
        color="blue",
        avatar=AvatarType(
            accessoriesType="Glasses",
            backgroundColor="PastelBlue",
            clotheColor="NavyBlue",
            clotheType="Hoodie",
            eyeType="Default",
            eyebrowType="UpDown",
            hairColor="Black",
            mouthType="Smile",
            skinColor="Light",
            topType="LongHairStraight",
        )
    ),
    Persona(
        id="2",
        name="Liam",
        role="environment",
        color="green",
        avatar=AvatarType(
            accessoriesType="None",
            backgroundColor="PastelGreen",
            clotheColor="ForestGreen",
            clotheType="TShirt",
            eyeType="Default",
            eyebrowType="Default",
            hairColor="Brown",
            mouthType="Default",
            skinColor="Medium",
            topType="ShortHairShortCurly",
        )
    ),
    Persona(
        id="3",
        name="Ava",
        role="education",
        color="yellow",
        avatar=AvatarType(
            accessoriesType="Headphones",
            backgroundColor="PastelYellow",
            clotheColor="Purple",
            clotheType="Sweater",
            eyeType="Happy",
            eyebrowType="DefaultNatural",
            hairColor="Blonde",
            mouthType="Smile",
            skinColor="Light",
            topType="ShortHairShortFlat",
        )
    ),
    Persona(
        id="4",
        name="Noah",
        role="culture",
        color="purple",
        avatar=AvatarType(
            accessoriesType="Beanie",
            backgroundColor="PastelPurple",
            clotheColor="Maroon",
            clotheType="Jacket",
            eyeType="Default",
            eyebrowType="Default",
            hairColor="Auburn",
            mouthType="Twinkle",
            skinColor="Pale",
            topType="ShortHairShortRound",
        )
    ),
    Persona(
        id="5",
        name="Emma",
        role="economics",
        color="green",
        avatar=AvatarType(
            accessoriesType="Scarf",
            backgroundColor="PastelGreen",
            clotheColor="Black",
            clotheType="Coat",
            eyeType="Default",
            eyebrowType="UpDown",
            hairColor="Black",
            mouthType="Twinkle",
            skinColor="Pale",
            topType="LongHairMiaWallace",
        )
    ),
    Persona(
        id="6",
        name="Lucas",
        role="science",
        color="orange",
        avatar=AvatarType(
            accessoriesType="None",
            backgroundColor="PastelOrange",
            clotheColor="White",
            clotheType="LabCoat",
            eyeType="Surprised",
            eyebrowType="DefaultNatural",
            hairColor="Brown",
            mouthType="Twinkle",
            skinColor="Light",
            topType="ShortHairShortFlat",
        )
    ),
    Persona(
        id="7",
        name="Mia",
        role="politics",
        color="blue",
        avatar=AvatarType(
            accessoriesType="Earrings",
            backgroundColor="PastelBlue",
            clotheColor="NavyBlue",
            clotheType="Blazer",
            eyeType="Default",
            eyebrowType="UpDown",
            hairColor="Black",
            mouthType="Twinkle",
            skinColor="Pale",
            topType="LongHairStraight",
        )
    ),
    Persona(
        id="8",
        name="Ethan",
        role="social",
        color="purple",
        avatar=AvatarType(
            accessoriesType="None",
            backgroundColor="PastelPurple",
            clotheColor="Gray02",
            clotheType="CasualShirt",
            eyeType="DefaultNatural",
            eyebrowType="Default",
            hairColor="Auburn",
            mouthType="Twinkle",
            skinColor="Pale",
            topType="ShortHairFrizzle",
        )
    )
]

chatrooms: List[ChatRoom] = [
    ChatRoom(
        id="0",
        participants=[],
        messages=[]
    ),
]